# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CalcGeometryParts.py
# Created on: 2020-08-27 13:25:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CalcGeometryParts <WLFW_Blandings_ProjectBndy__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
WLFW_Blandings_ProjectBndy__2_ = arcpy.GetParameterAsText(0)
if WLFW_Blandings_ProjectBndy__2_ == '#' or not WLFW_Blandings_ProjectBndy__2_:
    WLFW_Blandings_ProjectBndy__2_ = "WLFW_Blandings_ProjectBndy" # provide a default value if unspecified

# Local variables:
WLFW_Blandings_ProjectBndy__3_ = "WLFW_Blandings_ProjectBndy"

# Process: Add Geometry Attributes
arcpy.AddGeometryAttributes_management(WLFW_Blandings_ProjectBndy__2_, "PART_COUNT;POINT_COUNT", "", "", "")

